name: "CLA Check"

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

on:
  pull_request:
    types: [opened, synchronize, closed]
  issue_comment:
    types: [created]

jobs:
  call-cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/vyos/vyos-cla-signatures/blob/current/README.md'
          branch: 'current'
          allowlist: 'vyosbot,pre-commit-ci,dependabot,codecov,mergify,netlify'
          remote-organization-name: 'vyos'
          remote-repository-name: 'vyos-cla-signatures'