name: Trigger to build a deb package from repo

on:
  pull_request:
    types:
      - closed
    branches:
      - current
  workflow_dispatch:

jobs:
  trigger-build:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "PACKAGE_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Trigger build for ${{ env.PACKAGE_NAME }}
        uses: vyos/vyos-workflow-testing/.github/workflows/trigger-package-build.yml@main
        with:
            branch: ${{ github.ref_name }}
            package_name: ${{ env.PACKAGE_NAME }}
            REF: main # optinal because the default value is main
        secrets:
            REMOTE_OWNER: ${{ secrets.REMOTE_OWNER }}
            REMOTE_REUSE_REPO: ${{ secrets.REMOTE_REUSE_REPO }}
            GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
            PAT: ${{ secrets.PAT }}