name: Trigger VPP build

on:
  workflow_dispatch:

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger VPP build
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REUSE_REPO }}/actions/workflows/build-package.yml/dispatches \
            -d '{"ref": "main", "inputs":{"package_name":"vpp", "gpg_key_id": "${{ secrets.GPG_KEY_ID }}", "package_branch": "current", "pat":"${{ secrets.PAT }}"}}'