name: Trigger Docker image build

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  track-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout vyos/vyos-build repo
        uses: actions/checkout@v4
        with:
          repository: vyos/vyos-build
          ref: current

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: current
          filters: |
            docker-dir:
              - 'docker/**'

      - name: Trigger Docker image build for current
        if: ${{ !steps.changes.outputs.DOCKER_DIR }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REUSE_REPO }}/actions/workflows/trigger-docker-image-build.yml/dispatches \
            -d '{"ref": "docker-container", "inputs":{"branch":"current", "environment":"production"}}'