name: Workflow to update a version file

on:
  workflow_dispatch:

jobs:
  file_update:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: "Create version.json"
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "version.json"
          json: |
            [
              {
                "url": "https://github.com/vyos/vyos-nightly-build/releases/download/1.5-rolling-202503031030/vyos-1.5-rolling-202503031030-generic-amd64.iso",
                "version": "1.5-rolling-202503031030",
                "timestamp": "2025-03-03T10:30:48Z"
              }
            ]

      - name: "Create autocommit and tag"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          tagging_message: 1.5-rolling-202503031030
          commit_message: 1.5-rolling-202503031030
          commit_author: "vyosbot <autobuild@vyos.net>"

      - name: Update version.json in the remote repo
        run: |
          git clone https://github.com/vyos/vyos-workflow-version-tmp.git
          cd vyos-workflow-version-tmp
          cp -p ../version.json .
          git config --global user.name "vyosbot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.json
          git commit -m "1.5-rolling-202503031030"
          git tag 1.5-rolling-202503031030
          git push https://x-access-token:${{ secrets.PAT }}@github.com/vyos/vyos-workflow-version-tmp.git main --tags
          

