name: Workflow to update a version file

on:
  workflow_dispatch:

jobs:
  file_update:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: "Create version.json"
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "version.json"
          json: |
            [
              {
                "url": "https://github.com/vyos/vyos-nightly-build/releases/download/1.5-rolling-202503030030/vyos-1.5-rolling-202503030030-generic-amd64.iso",
                "version": "1.5-rolling-202503030030",
                "timestamp": "2025-03-03T00:30:48Z"
              }
            ]

      - name: "Release publishing: create autocommit and tag"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          tagging_message: 1.5-rolling-202503030030
          commit_message: 1.5-rolling-202503030030
          commit_author: "vyosbot <autobuild@vyos.net>"

